{
    "config": {
        "error": {
            "cannot_connect": "Falha ao conectar, tente novamente",
            "unknown": "Erro inesperado"
        },
        "step": {
            "user": {
                "data": {
                    "source_1": "Nome da fonte #1",
                    "source_2": "Nome da fonte #2",
                    "source_3": "Nome da fonte #3",
                    "source_4": "Nome da fonte #4",
                    "source_5": "Nome da fonte #5",
                    "source_6": "Nome da fonte #6"
                },
                "title": "Conecte-se ao dispositivo"
            }
        }
    }
}